leaf.name=com.sankuai.leaf.opensource.test
leaf.segment.enable=true
leaf.jdbc.url=jdbc:postgresql://127.0.0.1:5432/local_testdb
leaf.jdbc.driver=org.postgresql.Driver
leaf.jdbc.username=postgres
leaf.jdbc.password=postgres;123

leaf.snowflake.enable=false
#leaf.snowflake.zk.address=
#leaf.snowflake.port=
